### ISSUE TITLE
super$getDatabaseName() in PostgresResourceConnector.R

### ISSUE THREAD

**Issue by IulianD** [obiba/resourcer#3]
Hello, I try to load a Postgres resource table into a dataframe like this:
`datashield.assign.resource(opals, 'concept', 'omop_test.vocab_concept')`
`datashield.assign.expr(opals, 'concept2', quote(as.resource.data.frame(concept)))`
(btw is this the correct way to go about that?)
And I get this error:
`[1] "Command 'as.resource.data.frame(concept)' failed on 'omop_test': Error while evaluating 'is.null(base::assign('concept2', value={resourcer::as.resource.data.frame(concept)}))' -> Error in strsplit(url$path, split = \"/\") : \n  argument \"url\" is missing, with no default\n"`
Quick glance PostgresResourceConnector.R and it seems that at line 36:
`dbname = super$getDatabaseName())`
should actually be:
`dbname = super$getDatabaseName(url))`
(I might be wrong, I'm far from understanding the package - working on it though)

Also, if I got the datashield command right... why "as.resource.data.frame" and not "as.data.frame.resource"?

Cheers,
Iulian

**Comment by ymarcon** [comment]
You are right, `url` was missing.

* `as.resource.data.frame()` is the DS client function being declared, which turns a `ResourceClient` object (result of the assignment) into a data.frame. 
* `as.data.frame.resource()` is a S3 dispatch function (of `as.data.frame()`) that turns a `resource` object into a data.frame. The equivalent of the previous function is in fact `as.data.frame.ResourceClient()`.

**Comment by IulianD** [comment]
Thanks for the quick reply and the explanations.
It does work indeed with a quick fix but it doesn't allow me to go too far with datashield (or I should say dsBase), I think because the resulting object has 3 classes:
`> ds.class('concept2')`
`$omop_test`
[`1] "tbl_df"     "tbl"        "data.frame"`
`> ds.summary('concept2')`
`$omop_test`
`[1] "INVALID object!"`
Problem lies with the validation function in dsBase (isValidDS), it uses plain equality tests for classes, implicitly assuming uniqueness, that is:
`if(class(obj) == "data.frame" | class(obj) == "matrix"){` etc, etc
I'll take it up with our friends over at Datashield, thank you again!
Best,
Iulian

**Comment by ymarcon** [comment]
It is because dsBase does not handle object with multiple classes properly. The solution is to use the [strict](https://github.com/obiba/resourcer/blob/master/R/datashield.R#L6) parameter:

```
datashield.assign.expr(opals, 'concept2', quote(as.resource.data.frame(concept, strict = TRUE)))
```

**Comment by IulianD** [comment]
Strict, of course! And I had read that piece of doc but it didn't click :). Thanks!

**Comment by ymarcon** [comment]
Yep, default is FALSE because I expect that some day dsBase will compatible with tidyverse / dplyr : turning a SQL table into an in-memory data frame would not be an efficient process when working with (very) large datasets.
